//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkCostCalculator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49")]
        public double ColorCartridgeCost {
            get {
                return ((double)(this["ColorCartridgeCost"]));
            }
            set {
                this["ColorCartridgeCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49")]
        public double BlackCartridgeCost {
            get {
                return ((double)(this["BlackCartridgeCost"]));
            }
            set {
                this["BlackCartridgeCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22.5")]
        public double Color_ml {
            get {
                return ((double)(this["Color_ml"]));
            }
            set {
                this["Color_ml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29.1")]
        public double Black_ml {
            get {
                return ((double)(this["Black_ml"]));
            }
            set {
                this["Black_ml"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double ColorConst1 {
            get {
                return ((double)(this["ColorConst1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public double ColorConst2 {
            get {
                return ((double)(this["ColorConst2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1E-09")]
        public double ColorConst3 {
            get {
                return ((double)(this["ColorConst3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public double BlackConst1 {
            get {
                return ((double)(this["BlackConst1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public double BlackConst2 {
            get {
                return ((double)(this["BlackConst2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1E-09")]
        public double BlackConst3 {
            get {
                return ((double)(this["BlackConst3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp\\inklevels.xml")]
        public string InkLevelsPath {
            get {
                return ((string)(this["InkLevelsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp\\ProductUsageDyn.xml")]
        public string ProductUsageDynPath_xml {
            get {
                return ((string)(this["ProductUsageDynPath_xml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp\\ConsumableConfigDyn.xml")]
        public string ConsumableConfigDynPath_xml {
            get {
                return ((string)(this["ConsumableConfigDynPath_xml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Terry\\Documents\\Visual Studio 2015\\Projects\\InkCostCalculator\\InkCostCal" +
            "culator\\bin\\Debug\\ConsumableConfigDyn_get.bat")]
        public string ConsumableConfigDyn_get_bat {
            get {
                return ((string)(this["ConsumableConfigDyn_get_bat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Terry\\Documents\\Visual Studio 2015\\Projects\\InkCostCalculator\\InkCostCal" +
            "culator\\bin\\Debug\\ProductUsageDyn_get_afinia.bat")]
        public string ProductUsageDyn_get_afinia_bat {
            get {
                return ((string)(this["ProductUsageDyn_get_afinia_bat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp\\jobs.csv")]
        public string JobFilePath {
            get {
                return ((string)(this["JobFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Label Color Cost,Total Color Cost,Number of Color Labels,Color ml Used,Label Blac" +
            "k Cost,Total Black Cost,Number of Black Label,Black ml Used")]
        public string JobFileHeader {
            get {
                return ((string)(this["JobFileHeader"]));
            }
        }
    }
}
